export const menu=[
    {
        link:'/',
        name:'Home'
    },{
        link:'/apps',
        name:'Apps'
    },{
        link:'/blog',
        name:'Blog'
    },{
        link:'/bookmarks',
        name:'Bookmarks'
    },{
        link:'/resources',
        name:'Resources'
    },{
        link:'/tweets',
        name:'Tweets',
        mobile:true
    },{
        link:'/books',
        name:'Books',
        mobile:true
    },{
        link:'/notes',
        name:'Notes',
        mobile:true
    }
]